### ISSUE TITLE
PIP installation does not work.

### ISSUE THREAD

**Issue by 13steinj** [niklasb/webkit-server#19]
PIP installation (for at least Python 3, on Ubuntu Trusty) does not work. In the end it saves a file `webkit_server.py`, but other modules (such as dryscrape) can't find it properly.

Installing via cloning the repo and then manually running `python3 setup.py develop` does work though.

**Comment by askona** [comment]
I got the same problem with py27

**Comment by tristantao** [comment]
Same issue with OS X 10.10.5, py27, scrapy installer won't find it.

**Comment by tristantao** [comment]
The issue wasn't with the webkit-server, but rather qt. An older installation of qt (mine was 4.7.4) had some path issues. That was fixed by updating the qt installation (mine is included in Anaconda) done via (I wanted to stay in 4.0 so I went with 4.8.6):

`conda update conda
conda install -c anaconda qt=4.8.6 `

webkit-server installed fine afterwards. Moreover this all started when I tried to install [dryscrape](https://github.com/niklasb/dryscrape). Hopefully I'm finally out of the wild package chase...

**Comment by cameronkruse** [comment]
@tristanta any updates on your solution? I tried what you recommended, but I'm still having issues installing webkit-server. Also running into this via the dryscape package install process

**Comment by winnerineast** [comment]
I have the same issue with qt 4.8.7, python 2.7(anaconda virtual environment), xcode 8.2.1 when I installed both dryscrape and webkit-server from source code of github.

**Comment by tristantao** [comment]
@cameronkruse Yea the solution worked fine for me. I just had to make sure that the proper version of qt was installed. It got complicated when certain packages required it to be newer than certain versions, while other packages required it to be older (webkit).
